### ISSUE TITLE
Use of focus() is causing undesired scrolling

### ISSUE THREAD

**Issue by Thurst-ft** [Financial-Times/o-tabs#13]
@AlbertoElias  @kaelig Having updated the o-tabs dependency on the sign-up-app we are getting undesired scrolling. It looks like it's caused by the use of focus() in the showPanel method. 

We need it to remain static but not sure it there are cases where the default scrolling might be reuqired.

**Comment by AlbertoElias** [comment]
@kaelig If focus() is important, maybe we should keep the scroll position and set it again after focusing?

**Comment by kaelig** [comment]
It's pretty important for accessibility reasons. The code proposed in dbd75f4 should do the trick!

**Comment by kaelig** [comment]
Fixed in v1.4.5
