### ISSUE TITLE
Tabs should be pressable (i.e. press enter to select)

### ISSUE THREAD

**Issue by ironsidevsquincy** [Financial-Times/o-tabs#25]
General question, why is the tab itself made focusable, rather than leaving the link as is and focusable?

If this is expected behaviour, than when keyboard-tabbing to the tab, it should be selectable (e.g. by pressing enter)

**Comment by AlbertoElias** [comment]
Tabs should be pressable, so that is a bug. Could you rename the issue?

**Comment by ironsidevsquincy** [comment]
Will do. Still interested in why the tabindex is fiddled to make the tab focusable though...

**Comment by AlbertoElias** [comment]
Because the tab is a navigation element on the page and we'd like people to be able to use the keyboard to move around the page. I'm not sure I get why that can be weird

**Comment by ironsidevsquincy** [comment]
Because the links inside the tab (using the example markup from the docs) are already navigatable and pressable, via keyboard. So we're cancelling this default behaviour and forcing it onto the tab (`li`) element. 

Seems strange to fight against what the browser gives you for free to implement our navigation

**Comment by triblondon** [comment]
I don't feel strongly about this.  The visual effect of focusing the entire tab is probably nicer, but probably not worth it if the alternative is zero-effort to maintain.

**Comment by GlynnPhillips** [comment]
Looks like this work has been done by @andygout in [#42](https://github.com/Financial-Times/o-tabs/pull/42)
