### ISSUE TITLE
Exception when using config

### ISSUE THREAD

**Issue by roland-vachter** [Financial-Times/o-tabs#33]
Using the code snippet from the documentation

```
const Tabs = require('o-tabs');
const tabsObjects = Tabs.init({
    disableFocus: false
});
```

throws the following error:

`Tabs.js:223Uncaught SyntaxError: Failed to execute 'querySelector' on 'Document': '[object Object]' is not a valid selector.`

**Comment by AlbertoElias** [comment]
.init supports two parameters, the first is the element where to look for tabs, the second is a config option. You're passing the latter to the former

**Comment by roland-vachter** [comment]
I'm just using the example from the documentation. Then the documentation is wrong.

**Comment by AlbertoElias** [comment]
Opened #35 to fix it
