### ISSUE TITLE
Bug: Can not create a fake tab which has no panel

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/o-tabs#54]
The Tooling Team were trying to have a tab link to an external page and came across this issue.

Demo of the issue: http://output.jsbin.com/muvevuvoqi/

An error is thrown in the console: `Cannot read property 'setAttribute' of undefined`

Even without the error, we would need to update the clickHandler method to fallback to the native event handler when the `href` is not an in-page link. -- https://github.com/Financial-Times/o-tabs/blob/master/src/js/Tabs.js#L165-L172

**Comment by notlee** [comment]
Hey @AlanTurner, do all your tabs point to external links or is some content also tabbed on-page? We can enable links within a tab-like interface for you but wouldn't recommend it from a semantic or accessibility point of view. Have you considered using http://registry.origami.ft.com/components/o-hierarchical-nav@5.0.0?

**Comment by AlanTurner** [comment]
they are internal links within the same application (or lambda's in our case)...  we are trying to reduce our page weight and the tabs cause some flickering when the content hides.. so Ideally I like the tabs view but have links to new page reloads...  the other navs is a bit ugly for what we want..

**Comment by alicebartlett** [comment]
Hi @AlanTurner, we've fixed and released this now, as of version 4.0.1. Give us a shout if you need anything else!
