### ISSUE TITLE
Annoying scroll to first tab on page load

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-tabs#64]
On dewey we use the `data-o-tabs-update-url="true"` option, because we want people to be able to bookmark tabs.

This has the annoying side effect of causing the page to scroll down on page load because o-tabs sets the url's has to the name of the first tab, and then 'navigates' to that tab by scrolling down:
![o-tabs](https://user-images.githubusercontent.com/447559/41857054-79070138-788e-11e8-9cd2-694f6dde35e3.gif)

It'd be good to prevent this. Couple of ideas:

- Allow setting `data-o-tabs-update-url="onchange"` to only alter the url in response to a user changing tabs, never on init
- Never change the url on init (unless a tab other than the first one is configured to be the tab to load on init)

**Comment by notlee** [comment]
Hey @wheresrhys, I've updated `o-tabs` to never change the url on init (v4.2.0).
