### ISSUE TITLE
Custom events not supported in IE8

### ISSUE THREAD

**Issue by jamesnicholls** [Financial-Times/o-tabs#9]
Even with the CustomEvent polyfill, IE8 still doesn't support document.createEvent, so the custom event this module fires will not work in IE8.

**Comment by kaelig** [comment]
@jamesnicholls can you still reproduce this bug?

**Comment by jamesnicholls** [comment]
@kaelig No, this has been fixed.

**Comment by kaelig** [comment]
Cheers, I can close it then.
